# Header
menu:
  Home: /
  Logos: /tags/Logos
  Posters: /tags/Posters
  Banners: /tags/Banners

# Default post title
default_post_title: Untitled

# Default post cover index page
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page
default_cover_detail: "http://placehold.it/1300x500"

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://www.twitter.com/pujamittal_
facebook_url: https://www.facebook.com/
behance_url: https://www.behance.net/pujamittal
googleplus_url: 
dribble_url: 
rss_url:
